version: "3.1"

services:

    db:
        image: mariadb
        restart: unless-stopped
        environment:
            - "MYSQL_DATABASE=pterodactyl"
            - "MYSQL_PASSWORD=pterodactyl"
            - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
            - "MYSQL_USER=pterodactyl"
        networks:
            - traefik
            - default
        volumes:
            - db:/var/lib/mysql

    http:
        build:
            context: services/http
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - "php"
        expose:
            - 80
        networks:
            - traefik
            - default
        volumes:
            - env:/var/www/html/env
            - panel:/var/www/html/pterodactyl
            - storage:/var/www/html/pterodactyl/storage

    php:
        build:
            context: services/php
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - "db"
        networks:
            - default
        volumes:
            - env:/var/www/html/env
            - panel:/var/www/html/pterodactyl
            - storage:/var/www/html/pterodactyl/storage

    redis:
        image: redis:alpine
        restart: unless-stopped
        networks:
            - default

volumes:
  db:
  env:
  panel:
  storage:

networks:
    default:
        driver: bridge
    traefik:
        external: true
